name: Deploy to Vultr

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up SSH key for accessing Vultr server
      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VULTR_SSH_PRIVATE_KEY }}

      # Install Node.js 20.14.0
      - name: Set up Node.js 20.14.0
        uses: actions/setup-node@v3
        with:
          node-version: '20.14.0'

      # Deploy to Vultr Server
      - name: Deploy to Vultr Server
        run: |
          ssh -o StrictHostKeyChecking=no admin@${{ secrets.VULTR_SERVER_IP }} "bash -l -c 'cd RFID && git pull && yarn install && yarn build && pm2 restart piyucheckpoint'"
